BookSharing/BookSharing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MainApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookSharing/MainApp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signin', views.signin, name='signin'),
    path('about', views.about, name='about'),
    path('chat', views.chat, name='chat'),
    path('lib', views.lib, name='lib'),
    path('account', views.account, name='account'),
    path('logout', views.logout, name='logout'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('edit/<int:id>/', views.edit),
]

BookSharing/MainApp/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.db.models.signals import post_save
from django.dispatch import receiver

class Books(models.Model):
    image = models.FileField(null=True, blank=True)
    book = models.CharField(max_length=120)
    dis = models.CharField(max_length=120)
    cont = models.CharField(max_length=130)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)

BookSharing/MainApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Books


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

class Addbook(forms.ModelForm):
    class Meta:
        model = Books
        fields = ['image','book','dis','cont',]

BookSharing/MainApp/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm, Addbook
from django.contrib import auth
from django.http import HttpResponseRedirect,HttpResponseNotFound
from django.forms import modelformset_factory
from .models import Books
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, logout, login 


def index(reqest):
    book = Books.objects.all()
    return render(reqest, 'index.html', {'book' : book})



def signin(reqest):
    if reqest.method == 'POST':
        form = UserRegisterForm(reqest.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(reqest, f'hi{username}')
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'],)
            user.backend = "django.contrib.auth.backends.ModelBackend"
            login(reqest, user)
            return HttpResponseRedirect('/')
    else:
        form = UserRegisterForm()
    return render(reqest,'registration/signin.html', {'form': form})

def about(reqest):
    return render(reqest,'about.html')

def chat(reqest):
    return render(reqest,'chat.html')

@csrf_exempt
def lib(reqest):
    form = Addbook(reqest.POST or None, reqest.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user_id = reqest.user
        instance.save()
        return HttpResponseRedirect('/')  
    book = Books.objects.filter(user_id=reqest.user)
    return render(reqest,'lib.html',{'form' : form,'book': book})

def account(reqest):
    return render(reqest,'account.html')

def logout(reqest):
	auth.logout(reqest)
	return HttpResponseRedirect('/')

def delete(reqest,id):
    try:

        book = Books.objects.get(id=id)
        book.delete()
        return HttpResponseRedirect("/lib")
    except Books.DoesNotExist:
        return HttpResponseNotFound("<h2>Books not found</h2>")

def edit(reqest, id):
    try:
        book = Books.objects.get(id=id)
        if reqest.method == "POST":
            book.cont = reqest.POST.get("cont")
            book.dis = reqest.POST.get("dis")
            book.book = reqest.POST.get("book")
            book.image = reqest.POST.get("image")
            book.save()
            return HttpResponseRedirect("/lib")
        else:
            return render(reqest, "test.html", {"book": book})
    except Books.DoesNotExist:
        return HttpResponseNotFound("<h2>Books not found</h2>")

BookSharing/MainApp/templates/about.html
<!DOCTYPE html>
	<head>
		{% include 'includes/header.html' %}
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/about.css' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<title>О нас</title>
		<link rel="shortcut icon" type="image/png">
		<style type="text/css">
		div.header {
			height: 500px
			width: 300px; /* Ширина слоя 
			padding: 10px; /* Поля вокруг текста */
			background: white; /* Цвет фона */
			font-family: Roboto;
			margin-top: -5vh;
			border: 1px solid #4caf50;
			box-shadow: 0 0 5px;
			}
		
		.btn-primary {
			background-color: #4caf50;
			color: white;
			margin-left: 10px;
			font-family: Roboto;

		}
			
		.block {
			width: 800px;
			height: 600px;
			position: absolute;
			top: 50%;
			left: 30%;
			margin: -125px 0 0 -125px;
			background-color: white;
			border: 3px solid #4caf50;
			box-shadow: 0 0 10px;
			font-family: Roboto;
		}

			
		</style>
	</head>
	<body>

		<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
		<script src="{% static 'js/common.js' %}"></script>
		<BODY bgcolor="white" text="black">
		<div class = 'wrapper'>
		<div class = 'header'><h1 align="center" style="font-family: 'Montserrat', sans-serif;">О нас</h1></div>
		
		<div class="block"> <h4 align = center>Другая инфа</div>
	</body>
</html>

BookSharing/MainApp/templates/account.html
<!DOCTYPE html>
	<head>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/account.css' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<title>Аккаунт</title>
		<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
	</head>
	<body>
		{% include 'includes/header.html' %}
		<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>	
		<script src="{% static 'js/common.js' %}"></script>
	</body>
</html>

BookSharing/MainApp/templates/chat.html
<!DOCTYPE html>

<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/chat.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Чат</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" />
</head>

<body>
	{% include 'includes/header.html' %}

	<div class="row">
		<div class="z-depth-1 col s12 m8 offset-m2 l4 offset-l4" id="maincontainer">
			<div class="hat-field blue">

			</div>
			<div class="message-field">
				<div class="row">
					<div class="left message z-depth-1">Hello! Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
						aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
						laborum.</div>
				</div>
				<div class="row">
					<div class="right green message z-depth-1">Hello! Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
						nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
						est laborum.</div>
				</div>
				<div class="row">
					<div class="left message z-depth-1">Hello!</div>
				</div>
				<div class="row">
					<div class="right green message z-depth-1">Hello!</div>
				</div>
				<div class="row">
					<div class="left message z-depth-1">Hello!</div>
				</div>
				<div class="row">
					<div class="right green message z-depth-1">Hello!</div>
				</div>
				<div class="row">
					<div class="left message z-depth-1">Hello!</div>
				</div>
			</div>
			<div class="action-field">
				<div class="row valign-wrapper">
					<div class="col s10">
						<div class="input-field">
							<textarea id="textarea1" class="materialize-textarea"></textarea>
							<label for="textarea1">Textarea</label>
						</div>
					</div>
					<div class="col s2 valign-wrapper">
						<a class="btn-floating waves-effect waves-light green"><i class="material-icons">send</i></a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script src="{% static 'js/common.js' %}"></script>
</body>

</html>

BookSharing/MainApp/templates/includes/header.html
<header class="unselectable">
{% load static %}
<link rel="stylesheet" href="{% static 'css/header.css' %}"></link>
<div class="navbar-fixed hide-on-small-only">
<nav>
  <div class="navbar-fixed nav-wrapper blue-grey darken-3">
    <div class="container">
      <i class="right material-icons dropdown-trigger" data-target="dropdown1">menu</i>
      <!-- Dropdown Structure -->
      <ul id='dropdown1' class='dropdown-content'>
        {% if user.is_authenticated %}
        <li><a href="/lib" class="white-text waves-effect blue-grey darken-3">Мои книги</a></li>
        <!--<li><a href="/account" class="white-text waves-effect blue-grey darken-3">Настройки аккаунта</a></li>-->
        <li><a class="white-text waves-effect blue-grey darken-3" href='/logout' >Выйти</a></li>
        {% else %}
		    <li><a class="white-text waves-effect blue-grey darken-3" href='/accounts/login'>Войти</a></li>
        {% endif %}
        <li><a class="white-text waves-effect blue-grey darken-3" href="/about">О нас</a></li>
      </ul>
      <a href="/" class="brand-logo left">BookSharing</a>
    </div>
  </div>
</nav>
</div>
</header>

<ul id="slide-out" class="sidenav unselectable">
  {% if user.is_authenticated %}
  <li><div class="user-view">
    <div class="background blue-grey darken-3"></div>
    <!-- Тут фото-затычка-->
    <a href="/account"><img class="circle" src="{% static 'images/illuminatipizza.jpg' %}"></a>
    <a href="/account"><span class="white-text name">{{user.last_name}}, {{user.first_name}}</span></a>
    <a href="/account"><span class="white-text email">{{user.username}}</span></a>
  </div></li>
  <li><a class="waves-effect" href="/lib">Моя библиотека</a></li>
  <li><a class="waves-effect" href="/account">Настройки аккаунта</a></li>
  <li><a class="waves-effect" href="/about">О нас</a></li>
  <li><a class="waves-effect" href="/logout">Выйти</a></li>
  {% else %}
  <!-- Вот тут странный кусок говнокода, но работает он так, как я хочу -->
  <li><div class="user-view">
    <div class="background white"></div>
  </div></li>
  <li><a class="waves-effect" href="/accounts/login">Войти</a></li>
  <li><a class="waves-effect" href="/">Книги</a></li>
  <li><a class="waves-effect" href="/about">О нас</a></li>
  {% endif %}
</ul>

BookSharing/MainApp/templates/index.html
<!DOCTYPE html>

<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>BookSharing</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
</head>
<style type="text/css">
h3
{
  text-align: center;
}
</style>
<body>
	{% include 'includes/header.html' %}
	<h3>Обьявления</h3>
	<main>
	<div class="container main-container">
	<div class="row">
	{% for i in book %}

			<div class="col m4 l3">
				<div class="card medium">
					<div class="card-image waves-effect waves-block waves-light">
						{% if i.image.url != Null %}
						<img class="activator" src="{{i.image.url}}">
						{% else %}
						<img class="activator" src="{% static 'images/no-photo.png' %}">
						{% endif %}
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4">{{ i.book }}<i class="material-icons right">more_vert</i></span>
						<p>{{ i.dis }}</p>
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">Описание<i class="material-icons right">close</i></span>
						<p>{{ i.cont }}</p>
						<p>Эта книга пользлвателя {{i.user_id}}</p>
					</div>
				</div>
			</div>
	{% endfor %}
	</div>
	</div>
	</main>
	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script src="{% static 'js/common.js' %}"></script>
</body>

</html>

BookSharing/MainApp/templates/index2.html
<!DOCTYPE html>

<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>BookSharing</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
</head>

<body>
	{% include 'includes/header.html' %}
	<main>
	<div class="container main-container">
	<div class="row">
	{% for i in book %}

			<div class="col m4 l3">
				<div class="card medium">
					<div class="card-image waves-effect waves-block waves-light">
						{% if i.image.url != Null %}
						<img class="activator" src="{{i.image.url}}">
						{% else %}
						<img class="activator" src="{% static 'images/no-photo.png' %}">
						{% endif %}
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4">{{ i.book }}<i class="material-icons right">more_vert</i></span>
						<p>{{ i.dis }}</p>
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">Описание<i class="material-icons right">close</i></span>
						<p>{{ i.cont }}</p>
					</div>
				</div>
			</div>
	{% endfor %}
	</div>
	</div>
	</main>
	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script src="{% static 'js/common.js' %}"></script>
</body>

</html>

BookSharing/MainApp/templates/lib.html
<!DOCTYPE html>

<head>
	{% if not user.is_authenticated %}
	<meta http-equiv="refresh" content="0;URL=/"/>
	{% endif %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/lib.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Библиотека</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" />
</head>
<style type="text/css">
h3
{
  text-align: center;
}
</style>
<body>
	{% if user.is_authenticated %}
	{% include 'includes/header.html' %}
	<h3>Мои книги</h3>
	
	
		<main>
	<div class="container main-container">
	<div class="row">
		{% for i in book %}
			<div class="col m4 l3">
				<div class="card medium">
					<div class="card-image waves-effect waves-block waves-light">
						{% if i.image.url != Null %}
						<img class="activator" src="{{i.image.url}}">
						{% else %}
						<img class="activator" src="{% static 'images/no-photo.png' %}">
						{% endif %}
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4">{{ i.book }}<i class="material-icons right">more_vert</i></span>
						<p>{{ i.dis }}</p>
						<a href="/delete/{{i.id}}"><i class="material-icons prefix red-text">delete</i></a>
						<p></p>
						<a href="edit/{{i.id}}"><i class="material-icons prefix green-text">border_color</i></a>		
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">Описание<i class="material-icons right">close</i></span>
						<p>{{ i.cont }}</p>
					</div>
				</div>
			</div>
	{% endfor %}
	</div>
	</div>
	</main>
	<button class="fixed-action-btn btn-floating btn-large green modal-trigger" data-target="modal1"><i class="material-icons">add</i></button>
	<div id="modal1" class="modal unselectable">
			<div class="modal-content">
				<h5 class="center">Добавьте книгу</h5>
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
	
					<input type="hidden" name="csrfmiddlewaretoken" value="RK2gzlgmAb8fFU2cQi5cgVy9oUk43uCaNQMHVoZnbkaLBJ23IobeNxO2QoFwWYJT">
					<div class="row">
						<div class="input-field col s10 offset-s1">
							<i class="material-icons prefix green-text">book</i>
							<label for="id_book">Название</label>
							<input type="text" name="book" maxlength="20" required id="id_book">
						</div>
						<div class="input-field col s10 offset-s1">
							<i class="material-icons prefix green-text">account_circle</i>
							<label for="id_dis">Автор</label>
							<input type="text" name="dis" maxlength="120" required id="id_dis">
						</div>
						<div class="input-field col s10 offset-s1">
							<i class="material-icons prefix green-text">phone</i>
							<label for="id_cont">Контакты</label>
							<input type="text" name="cont" maxlength="30" required id="id_cont">
							<input type="hidden" name="form-0-id" id="id_form-0-id">
						</div>
						<div class="file-field input-field col s10 offset-s1">
							<i class="material-icons prefix green-text">photo</i>
							<input type="file" name="image" id="id_image">
							<div class="file-path-wrapper">
								<input class="file-path validate" type="text">
							</div>
							<label for="id_image">Фото</label>
						</div>
						<button class="green waves-effect waves-light btn col s8 offset-s2" type="submit">Добавить</button>
					</div>
				</form>
			</div>
		</div>
	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script src="{% static 'js/common.js' %}"></script>
	 {% else %}
	 <h1><a href="/accounts/login/">Ввойдите чтобы добавить книгу!!</a></h1>
	  {% endif %}
</body>
</html>

BookSharing/MainApp/templates/test.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Модели в Django</title>
</head>
<body class="container">
    <form method="POST">
        {% csrf_token %}
        <p>
            <label>Изменить фото</label><br>
            <input class="file-path validate" type="file" name="image" value="{{book.image}}" />
        </p>
        <p>
            <label>Изменить название</label><br>
            <input type="text" name="book" value="{{book.book}}" />
        </p>
        <p>
            <label>Изменить автора</label><br>
            <input type="text" name="dis" value="{{book.dis}}" />
        </p>
        <p>
            <label>Изменить контакты</label><br>
            <input type="text" name="cont" value="{{book.cont}}" />
        </p>
        <input type="submit" value="Сохранить" >
    </form>
</body>
</html>